### ISSUE TITLE
Incorrect 'array' type for `caddy.logging.encoders.filter` `fields` key

### ISSUE THREAD

**Issue by melink14** [abiosoft/caddy-json-schema#5]
`caddy.logging.encoders.filter`'s `field` key should take (according to the docs and practice) an object of field names to filters. However, when using the schema generated by this plugin it says `fields` should take an array and thus gives an error.

Caddy version v2.4.3

Caddy [full donwload URL](https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fabiosoft%2Fcaddy-yaml&p=github.com%2Fmastercactapus%2Fcaddy2-proxyprotocol&p=github.com%2Fabiosoft%2Fcaddy-json-schema&p=github.com%2Fmholt%2Fcaddy-l4&idempotency=16540498071478) with plugins.

Example correct logging section which gives a type error (for `common_log`) in vscode:
```
logging:
  logs:
    default:
      exclude:
        - http.log.access.stephie
    stephie:
      writer:
        filename: /srv/popple/log/access.log
        output: file
      encoder:
        fields:
          common_log:
            filter: delete
        format: filter
        wrap:
          format: json
          level_key: severity
          message_key: message
          time_key: timestampSeconds
      level: DEBUG
      include:
        - http.log.access.stephie
```
